export const calcButtons = [
    { button: "AC", className: "operation1", type: "C" },
    { button: "+/-", className: "operation1", type: "+/-" },
    { button: "%", className: "operation1", type: "op" },
    { button: "÷", className: "operation", type: "op" },
    { button: 7, className: "number", type: "num" },
    { button: 8, className: "number", type: "num" },
    { button: 9, className: "number", type: "num" },
    { button: "×", className: "operation", type: "op" },
    { button: 4, className: "number", type: "num" },
    { button: 5, className: "number", type: "num" },
    { button: 6, className: "number", type: "num" },
    { button: "-", className: "operation", type: "op" },
    { button: 1, className: "number", type: "num" },
    { button: 2, className: "number", type: "num" },
    { button: 3, className: "number", type: "num" },
    { button: "+", className: "operation", type: "op" },
    { button: 0, className: "number0", type: "num" },
    { button: ".", className: "number", type: "num" },
    { button: "=", className: "operation2", type: "=" },
  ];